name: Application check and build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-for-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Build Ubuntu app with PyInstaller
      run: |
        pip install PyInstaller
        pyinstaller --onefile --noconsole --name=MFNotepad src/mfnp/main.py
        cp src/mfnp/presend.jcl dist/
        cp src/mfnp/config.ini dist/

    - uses: actions/upload-artifact@v3.1.1
      with:
        name: MFNotepad-ubuntu
        path: dist/

  build-for-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      shell: pwsh
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
    - name: Lint with flake8
      shell: pwsh
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Build Windows app with PyInstaller
      shell: pwsh
      run: |
        pip install PyInstaller
        pyinstaller --onefile --noconsole --name=MFNotepad src/mfnp/main.py
        copy src/mfnp/presend.jcl dist/
        copy src/mfnp/config.ini dist/

    - uses: actions/upload-artifact@v3.1.1
      with:
        name: MFNotepad-windows
        path: dist/
